### ISSUE TITLE
Unable to debug plugin

### ISSUE THREAD

**Issue by LvffY** [getporter/hashicorp-plugins#4]
Hello

I'm trying to configure hashicorp plugins and have trouble with it. In my case, I'm trying to fetch secrets from my hashicorp vault server.

On this point, for now, I'm pretty sure this is one of my configuration that isn't working.

But while I'm trying to debug my config I'm adding the `--verbose debug` flag to my porter command.

Unfortunately, any of the debug/error lines show up on the console.

**Comment by LvffY** [comment]
On the other hand, I've just add the `verbosity: debug` line in my `~/.porter/config.yaml` file and have more lines on the output, so may be just a CLI issue ?

**Comment by carolynvs** [comment]
oh! Sorry I didn't notice when we were chatting, but the flag is `--verbosity=debug`, not verbose. Can you try that and let me know if you get the same additional output as when you changed the config file?

**Comment by LvffY** [comment]
Hello @carolynvs 

I tried this command `cp -f config.yaml $HOME/.porter/ && porter build && porter install placeholder/foobar --force --verbosity=debug` but nothing more of debug

**Comment by LvffY** [comment]
Hello @carolynvs 

Did you have time to look into this ? (or anyone else ^^').

I must confess that it would be a great help :)

**Comment by VinozzZ** [comment]
Hi @LvffY , sorry for the delay. I can look into this while @carolynvs is away. Do you mind to share the version of porter and the hashicorp plugin that you use?

**Comment by LvffY** [comment]
Hi @VinozzZ 

No problem for me :)

I tried this morning with all latest versions (i.e porter **1.0.4** and plugin version **1.0.0**)

**Comment by VinozzZ** [comment]
Hi there, I found the issue after some debugging and put up a PR for the fix. https://github.com/getporter/porter/pull/2505
One thing I want to point out is that the verbosity flag only controls how verbose the output is. The --debug is used to indicate that the bundle should run in "debug mode". In debug mode, porter sets the parameter PORTER_DEBUG to true, and the bundle, porter runtime and mixins may check this value to have the bundle behave differently than normal. The --debug is only applied to bundle action commands: install, uninstall, invoke, and upgrade.

Thank you for opening the issue and provide your porter version number. Feel free to try out the fix from that PR and let me know if that fixes your issue

**Comment by carolynvs** [comment]
@LvffY Porter v1.0.7 has a fix for --verbosity not being passed properly to the plugins. Please let us know if you run into any further problems!
